export default [
{date:"12-3-2020",
 setting : "russia",
 artist : "vinci",   
 type : "Painting",
},
{date:"12-4-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
},
{date:"12-5-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
},
{date:"12-6-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
},
{date:"12-7-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
},
{date:"12-8-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
},
{date:"12-9-2020",
setting : "russia",
artist : "vinci",   
type : "Painting",
}

]